/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Dorm-Room.glb -o components/DormRoom.jsx --transform --shadows 
Files: public/Dorm-Room.glb [74.37MB] > C:\Users\LENOMVO\Desktop\Projects\room-decor\components\Dorm-Room-transformed.glb [9.52MB] (87%)
*/
'use client'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dorm-Room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['(Cycles)_Emissive_Planes'].geometry} material={materials.PaletteMaterial001} position={[-1.33, 1.3, 3.356]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Ground_512x512mo001.geometry} material={materials.TX_Fab_Carpet01} position={[-1.851, 0, -2.852]} />
      <group position={[2.068, 0.12, 2.211]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Walls_Room02md.geometry} material={materials.TX_Walls_Standard01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Walls_Room02md_1.geometry} material={materials.TX_Walls_Parts01} />
      </group>
      <group position={[2.068, 3.2, 2.996]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Walls_Standard01Bmd001.geometry} material={materials.TX_Walls_Brick05} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Walls_Standard01Bmd001_1.geometry} material={materials.TX_Walls_Parts01} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_Threshold01mo002.geometry} material={materials.TX_Furn_Treshold01} position={[4.441, 2.057, -2.773]} />
      <group position={[-1.201, 0.161, -1.035]} rotation={[0, 1.396, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Post_Magazine01Bmd.geometry} material={materials.TX_Post_Magazine01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Post_Magazine01Bmd_1.geometry} material={materials.TX_Post_Magazine04} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Post_Magazine01Bmd_2.geometry} material={materials.TX_Post_Magazine08} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Win_RoomWin01mo.geometry} material={materials.TX_Win_Glass01} position={[0.185, 0.87, 3.093]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Agenda01mo.geometry} material={materials.TX_Acc_Agenda01} position={[-0.399, 0.681, 2.851]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Books01Bmo.geometry} material={materials.TX_Acc_Books01} position={[1.515, 0.975, 2.805]} rotation={[0, -1.484, 0]} scale={[1.003, 0.88, 1.298]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Notesmo.geometry} material={materials.TX_Acc_Notes} position={[-1.32, 0.44, -1.023]} rotation={[0, -1.404, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Pencil01mo.geometry} material={materials.TX_Acc_PencilJar01} position={[0.639, 0.005, 2.514]} rotation={[0, 1.484, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_PencilJar01mo.geometry} material={materials.TX_Acc_PencilJar01_Plastic} position={[0.16, 0.68, 2.872]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Pencilsmo.geometry} material={materials.TX_Acc_Pencils} position={[2.342, 0.681, 0.456]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_RingBinder02mo001.geometry} material={materials.TX_Acc_RingBinder01} position={[-0.598, 0.68, 2.807]} scale={[1, 1, 0.8]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_ShoesBox01mo001.geometry} material={materials.TX_Acc_ShoesBox04} position={[0.828, 0.68, 2.779]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Trashcan01mo.geometry} material={materials.TX_Acc_TrashCan01} position={[0.493, 0, 2.769]} rotation={[0, -1.134, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_Vase01mo.geometry} material={materials.TX_Acc_Vase01} position={[1.501, 1.13, 2.854]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Fab_BackPack01mo.geometry} material={materials.TX_Fab_BackPack01} position={[-1.48, 0.006, 0.707]} rotation={[0, 1.456, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Fab_Carpet05mo.geometry} material={materials.TX_Fab_Carpet05} position={[-1.137, 0.001, 0.583]} rotation={[0, Math.PI / 2, 0]} scale={[0.855, 0.95, 0.95]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Fab_Comforter04mo.geometry} material={materials.TX_Fab_Comforter04} position={[-2.173, 0.422, 1.745]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Fab_Pillow01mo.geometry} material={materials.TX_Fab_Pillow01} position={[-2.138, 0.567, 2.562]} rotation={[0, 1.571, 0]} scale={[0.8, 1, 1]} />
      <group position={[1.301, 0, 0.263]} rotation={[-Math.PI, Math.PI / 9, -Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Furn_ArmChair02md.geometry} material={materials.MT_Furn_ArmChair02} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Furn_ArmChair02md_1.geometry} material={materials.MT_Furn_ArmChair02_Metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_CoffeeTable03mo.geometry} material={materials.TX_Furn_CoffeeTable03} position={[-1.215, 0, -0.957]} rotation={[Math.PI, -1.396, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_Radiator01mo.geometry} material={materials.MT_Furn_Radiator01} position={[-2.929, 0.117, -0.691]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_RoomBed01mo.geometry} material={materials.MT_Furn_RoomBed01} position={[-2.173, 0.075, 1.733]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_RoomChestDrwr01A_Drmo.geometry} material={materials.TX_Furn_RoomDesk01} position={[1.876, 0.56, -1.484]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_RoomChestDrwr01A_Drmo001.geometry} material={materials.TX_Fab_VicClotheFolded01} position={[1.167, 0.579, 2.325]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_RoomDesk02mo.geometry} material={materials.TX_Furn_RoomDesk01} position={[1.162, 0.39, 2.808]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.98, 1, 1.2]} />
      <group position={[2.134, 0, -0.064]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Furn_StudentDesk04md.geometry} material={materials.TX_Furn_StudentDesk04} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Furn_StudentDesk04md_1.geometry} material={materials.TX_Furn_StudentDesk04_Metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Ground_128x256mo.geometry} material={materials.TX_Fab_Carpet01C} position={[0.24, 0.001, 1.639]} rotation={[0, Math.PI / 2, 0]} scale={[0.729, 1, 1.3]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Light_FairyLights02mo.geometry} material={materials.TX_Light_FairyLights02} position={[-2.782, 2.085, 2.967]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Light_WallStar01mo.geometry} material={materials.TX_Light_WallStar01_Emissive} position={[-1.437, 2.052, 2.965]} rotation={[-1.433, -0.141, 0.203]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_ArtBook01mo.geometry} material={materials.TX_Papers_ArtBook01} position={[1.36, 0.404, 0.124]} rotation={[3.141, -0.007, -3.088]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_ArtBook01mo001.geometry} material={materials.TX_Papers_JeffersonBook01} position={[1.21, 0.955, 2.791]} rotation={[1.607, -0.697, 1.642]} scale={[0.63, 1.089, 0.63]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_EmailJuliette01mo.geometry} material={materials.TX_Papers_VicGalleryLetter01} position={[-1.149, 0.444, -1.091]} rotation={[Math.PI, -1.134, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_MPAmo.geometry} material={materials.TX_Papers_MPAWrited01} position={[1.385, 0.681, 2.626]} rotation={[Math.PI, -0.262, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_WomensMagazine01mo.geometry} material={materials.TX_Papers_WomensMagazines01} position={[2.15, 0.681, -1.109]} rotation={[0, 1.571, 0]} />
      <group position={[2.5, 1.892, -1.452]} rotation={[0, -Math.PI / 2, 0]} scale={0.81}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Post_VicRoomFrame01md.geometry} material={materials.TX_Deco_Frame01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Post_VicRoomFrame01md_1.geometry} material={materials.TX_Post_VicRoomFrame01} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Post_VicRoomPoster04mo.geometry} material={materials.TX_Post_VicRoomPictures01} position={[-1.052, 1.783, 2.995]} rotation={[Math.PI, 0, Math.PI]} scale={1.4} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Post_WallSmallVert01Amo.geometry} material={materials.TX_Post_VicRoomPoster01} position={[1.162, 1.831, 2.995]} rotation={[Math.PI, 0, Math.PI]} scale={[2.867, 2.1, 2.1]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Tech_BluRay01Cmo.geometry} material={materials.TX_Tech_BluRay01} position={[2.11, 0.68, -1.846]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Tech_DVD01Dmo.geometry} material={materials.TX_Tech_DVD01} position={[1.355, 1.13, 2.778]} rotation={[0, -1.134, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Tech_MusicDock01mo.geometry} material={materials.TX_Tech_MusicDock01} position={[0.909, 1.133, 2.791]} rotation={[0, 0.087, 0]} scale={0.9} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Tech_USSocket01mo.geometry} material={materials.TX_Tech_SocketUS01} position={[0.353, 0.263, 2.996]} rotation={[Math.PI, 0, Math.PI]} />
      <group position={[2.234, 0.68, -1.484]} rotation={[0, -1.396, 0]} scale={0.742}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_WidescreenTv01md.geometry} material={materials.TX_Tech_WidescreenTv01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_WidescreenTv01md_1.geometry} material={materials.TX_Tech_WidescreenTv01_Emissive} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.TX_Papers_FlyerJeffExpo01.geometry} material={materials.TX_Papers_FlyerJeffExpo01_D} position={[0.776, 0.681, 2.483]} rotation={[Math.PI, -0.175, Math.PI]} scale={[0.079, 0.072, 0.065]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Deco_ReflectPlane01mo003.geometry} material={materials.TX_Deco_ReflectPlane01} position={[2.058, 0.221, 2.616]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_PencilsSupplies01Amo.geometry} material={materials.TX_Acc_PencilsSupplies01} position={[0.023, 0.68, 2.682]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Food_Glass01mo.geometry} material={materials.TX_Food_Glass01} position={[0.072, 0.681, 2.833]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Food_CoffeeCup01Cmo.geometry} material={materials.TX_Food_CoffeeCup01} position={[-1.47, 0.44, -0.764]} rotation={[-Math.PI, 1.222, -Math.PI]} />
      <group position={[0.126, 0.68, 2.52]} rotation={[Math.PI, -0.175, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Food_CoffeeCup01md.geometry} material={materials.TX_Food_CoffeeCup01_Liquid} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Food_CoffeeCup01md_1.geometry} material={materials.TX_Food_CoffeeCup01_Metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.ST_Papers_NotebookStack01mo.geometry} material={materials.TX_Papers_Notebooks01} position={[2.07, 0.687, 0.151]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.TX_E1_3C_VicRoom_Gazette_SP01.geometry} material={materials.TX_E1_3C_VicRoom_Gazette} position={[2.103, 0.71, 0.073]} rotation={[0, -Math.PI / 2, 0]} scale={0.3} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Post_VicRoomPainting01mo001.geometry} material={materials.TX_Post_FactorySmoke01} position={[-2.891, 0.906, -0.948]} rotation={[0, Math.PI / 2, 0]} scale={1.005} />
      <group position={[1.819, 0, 0.84]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Light_LampHalogen02md001.geometry} material={materials.TX_Light_LampHalogen02} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Light_LampHalogen02md001_1.geometry} material={materials.TX_Light_LampHalogen02_Metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Empty002.geometry} material={materials['Empty.001']} position={[-2.786, 1.527, 2.421]} rotation={[1.534, 0, -Math.PI / 2]} scale={0.182} />
      <mesh castShadow receiveShadow geometry={nodes.Empty004.geometry} material={materials['Empty.003']} position={[-2.798, 1.749, 1.791]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.125} />
      <mesh castShadow receiveShadow geometry={nodes.Empty008.geometry} material={materials['Empty.005']} position={[-2.798, 1.046, 1.672]} rotation={[1.612, 0, -Math.PI / 2]} scale={0.07} />
      <mesh castShadow receiveShadow geometry={nodes.Empty010.geometry} material={materials['Empty.009']} position={[-2.798, 1.542, 1.209]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.145} />
      <mesh castShadow receiveShadow geometry={nodes.Empty011.geometry} material={materials['Empty.007']} position={[-2.798, 1.208, 1.944]} rotation={[1.464, 0, -Math.PI / 2]} scale={0.073} />
      <mesh castShadow receiveShadow geometry={nodes.Empty013.geometry} material={materials['Empty.012']} position={[-2.915, 1.395, 0.102]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.122} />
      <mesh castShadow receiveShadow geometry={nodes.Empty015.geometry} material={materials['Empty.014']} position={[-2.798, 0.982, 1.209]} rotation={[1.47, 0, -Math.PI / 2]} scale={0.079} />
      <mesh castShadow receiveShadow geometry={nodes.Empty001.geometry} material={materials.Empty} position={[-2.798, 0.826, 2.411]} rotation={[1.466, 0, -Math.PI / 2]} scale={0.095} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Walls_RoomWin01mo002.geometry} material={materials.TX_Walls_Brick05} position={[2.068, 3.2, 2.996]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Furn_Sofa04mo.geometry} material={materials.TX_Furn_Sofa04} position={[-2.229, 0, -0.799]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_CamBoxe01_Amo.geometry} material={materials.TX_Acc_CamBoxe01} position={[2.377, 1.311, -0.219]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_RingBinder01mo.geometry} material={materials.TX_Acc_RingBinder01} position={[2.389, 1.703, -0.178]} rotation={[-0.751, 1.57, 2.288]} scale={[1.2, 1.2, 0.583]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Acc_ShoesBox01mo.geometry} material={materials.TX_Acc_ShoesBox01} position={[2.386, 1.921, -0.182]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Deco_CuddlyToy01mo.geometry} material={materials.TX_Deco_CuddlyToy01} position={[2.284, 1.211, 0.328]} rotation={[Math.PI, -0.143, Math.PI]} scale={[-1.21, 1.21, 1.21]} />
      <mesh castShadow receiveShadow geometry={nodes.ST_Tech_Camera05Bmo.geometry} material={materials.TX_Tech_Camera05} position={[2.369, 1.211, 0.113]} rotation={[0, -1.14, 0]} />
      <group position={[2.431, 1.211, -0.072]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_Lens01_Amd.geometry} material={materials.TX_Tech_Lens01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_Lens01_Amd_1.geometry} material={materials.TX_Tech_Lens01_Glass} />
      </group>
      <group position={[2.263, 1.327, 0.284]} rotation={[-1.348, -1.401, -1.773]}>
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_Lens01_Cmd.geometry} material={materials.TX_Tech_Lens01} />
        <mesh castShadow receiveShadow geometry={nodes.ST_Tech_Lens01_Cmd_1.geometry} material={materials.TX_Tech_Lens01_Glass} />
      </group>
      <group position={[-1.433, 0.535, 2.707]} rotation={[-1.575, 0.034, 2.824]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials['16_screen']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube009_1.geometry} material={materials.PaletteMaterial003} />
        <mesh castShadow receiveShadow geometry={nodes.Cube009_2.geometry} material={materials['16_wire']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube009_3.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Base001.geometry} material={materials['Material.001']} position={[-1.317, 0, 2.739]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.05} />
      <mesh castShadow receiveShadow geometry={nodes.Body.geometry} material={materials.Wood14} position={[-1.317, 0, 2.739]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.05} />
      <group position={[2.072, 0.681, -0.442]} rotation={[-Math.PI, 1.283, -Math.PI]} scale={1.304}>
        <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['Epson_Main Color']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube006_1.geometry} material={materials.Epson_RGB} />
        <mesh castShadow receiveShadow geometry={nodes.Cube006_2.geometry} material={materials.Epson_Indicator} />
        <mesh castShadow receiveShadow geometry={nodes.Cube006_3.geometry} material={materials.PaletteMaterial004} />
        <mesh castShadow receiveShadow geometry={nodes.Cube006_4.geometry} material={materials.Epson_overlay} />
      </group>
      <group position={[-0.916, 0.001, 1.717]} rotation={[0, 0.577, 0]} scale={0.797}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh009.geometry} material={materials['Black Plastic']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009_1.geometry} material={materials['White Metal']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009_2.geometry} material={materials['White Plastic']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009_3.geometry} material={materials['Fabric.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh009_4.geometry} material={materials.Lather} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dorm-Room-transformed.glb')
